### ISSUE TITLE
Change prettier for JS

### ISSUE THREAD

**Issue by ZuzaOsa** [scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver#35]
Change formatter settings, 4 spaces instead of 2.

**Comment by wprzytula** [comment]
Is this a change compared to Datastax driver's formatter settings?

**Comment by ZuzaOsa** [comment]
Yes, but running the default Prettier we already made changes to Datastax formatting.

**Comment by adespawn** [comment]
Keeping indent at 2 would keep it consistent with rust implementation...

**Comment by adespawn** [comment]
Last time I checked, the default indent for rust (which we are using) is 2

**Comment by wprzytula** [comment]
https://doc.rust-lang.org/beta/style-guide/index.html#indentation-and-line-width mentions 4 spaces.

**Comment by ZuzaOsa** [comment]
Yes, we will definitely need to change the default settings, metioned also in [PR#34](https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/pull/34).

**Comment by wprzytula** [comment]
> Well. The 2 indents is wat napi init has created. Maybe the default isn't recommended 😆

I'm getting more and more suspicious about napi-rs :stuck_out_tongue:

**Comment by adespawn** [comment]
> I'm getting more and more suspicious about napi-rs 😛 Not only is the documentation very lackluster, but also those defaults are strange...

It's still a bit better than neon's documentation :laughing:
