### ISSUE TITLE
Check space after `//` in JS Prettier

### ISSUE THREAD

**Issue by Stapox35** [scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver#65]
Add to prettier check space after comment `//`.
              Do we want to have a space after ``//``? And if so is it possible to check it in prietier?

_Originally posted by @adespawn in https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/pull/49#discussion_r1828144851_

**Comment by ZuzaOsa** [comment]
Prettier does not support adding space after ``//``: https://github.com/prettier/prettier/issues/5755. For this we would need to configure eslint.
