### ISSUE TITLE
Proper error throwing

### ISSUE THREAD

**Issue by adespawn** [scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver#88]
Currently NAPI allows to throw only few types of errors, but it's required that specific errors should be thrown in many places 

ex. https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/blob/bad25f7a837a434efa6aa3a0c50157c18e62ce46/test/integration/not-supported/client-execute-tests.js#L100-L114 

Add support for using custom errors from rust part of the driver

**Comment by PiotrJunior** [comment]
https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/pull/39#discussion_r1847382662
