### ISSUE TITLE
CI: have a step that prevents regressions wrt passing tests

### ISSUE THREAD

**Issue by wprzytula** [scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver#9]
Once we have some tests passing, we don't want to lose them after some changes. Hence, it makes sense to introduce a CI step that prevents regressions, i.e. rejects a PR that makes some tests which were previously passing fail.

**Comment by adespawn** [comment]
Considering, that currently some tests pass because of datastax driver code, I don't thing it's a good idea to add this (for now)

**Comment by wprzytula** [comment]
> Considering, that currently some tests pass because of datastax driver code, I don't thing it's a good idea to add this (for now)

Agreed. Let's keep it in mind, though, to take advantage of regressions detection as soon as possible.

**Comment by wprzytula** [comment]
Ref: #43

**Comment by wprzytula** [comment]
@adespawn What's the status of this?

**Comment by adespawn** [comment]
Coming back to that, I don't see how it would differ from ensuring there is green tick on GitHub actions status (aka. all tests have passed)

Either way, if I understand how GH works, this should be done as branch ruleset, as repo admin (and I don't have such permissions)

**Comment by wprzytula** [comment]
The way I understand our current approach to integration tests is that we only have those tests enabled that are expected to pass. So this is essentially resolved.
